// @formatter:off
object Version {
    val kotlin                  = "1.3.10"

    // Implementation
    val byte_buddy              = "1.9.6"
    val commons_codec           = "1.11"
    val commons_lang3           = "3.8.1"
    val commons_io              = "2.6"
    val dropwizard_metrics      = "4.0.3"
    val disruptor               = "3.4.2"
    val google_cloud_datasource = "1.56.0"
    val google_auth             = "0.12.0"
    val hazelcast               = "3.11.1"
    val http_client             = "4.5.6"
    val http_core               = "4.4.10"
    val hibernate_validator     = "6.0.13.Final"
    val jackson                 = "2.9.8"
    val jasypt                  = "1.9.2"
    val java_uuid               = "3.1.5"
    val jaxb                    = "2.3.1"
    val jjwt                    = "0.9.1"
    val log4j2                  = "2.11.1"
    val nebula                  = "5.0.0"
    val okhttp                  = "3.12.1"
    val opencsv                 = "4.4"
    val rx                      = "2.2.13"
    val reactor                 = "1.0.0.RELEASE"
    val rest_assured            = "3.2.0"
    val slf4j                   = "1.8.0-beta2"
    val spring_boot             = "2.1.1.RELEASE"

    // Test
    val assertj                 = "3.11.1"
    val junit                   = "5.3.2"
    val junit_platform          = "1.3.2"
    val mockito                 = "2.23.4"
    val mockito_kotlin          = "2.0.0"
}

object Lib {
    // Implementation
    val commons_codec           = "commons-codec:commons-codec:${Version.commons_codec}"
    val commons_lang3           = "org.apache.commons:commons-lang3:${Version.commons_lang3}"
    val commons_io              = "commons-io:commons-io:${Version.commons_io}"
    val dropwizard_healthchecks = "io.dropwizard.metrics:metrics-healthchecks:${Version.dropwizard_metrics}"
    val disruptor               = "com.lmax:disruptor:${Version.disruptor}"
    val google_cloud_datasource = "com.google.cloud:google-cloud-datastore:${Version.google_cloud_datasource}"
    val google_auth             = "com.google.auth:google-auth-library-appengine:${Version.google_auth}"
    val hazelcast               = "com.hazelcast:hazelcast:${Version.hazelcast}"
    val hazelcast_spring        = "com.hazelcast:hazelcast-spring"
    val http_client             = "org.apache.httpcomponents:httpclient:${Version.http_client}"
    val http_core               = "org.apache.httpcomponents:httpcore:${Version.http_core}"
    val hibernate_validator     = "org.hibernate.validator:hibernate-validator:${Version.hibernate_validator}"
    val jackson_core            = "com.fasterxml.jackson.core:jackson-core:${Version.jackson}"
    val jackson_annotations     = "com.fasterxml.jackson.core:jackson-annotations:${Version.jackson}"
    val jackson_databind        = "com.fasterxml.jackson.core:jackson-databind:${Version.jackson}"
    val jackson_kotlin          = "com.fasterxml.jackson.module:jackson-module-kotlin:${Version.jackson}"
    val jackson_jsr310          = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${Version.jackson}"
    val jackson_yaml            = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${Version.jackson}"
    val jasypt                  = "org.jasypt:jasypt:${Version.jasypt}"
    val java_uuid               = "com.fasterxml.uuid:java-uuid-generator:${Version.java_uuid}"
    val jaxb                    = "javax.xml.bind:jaxb-api:${Version.jaxb}"
    val jjwt                    = "io.jsonwebtoken:jjwt:${Version.jjwt}"
    val log4j2_core             = "org.apache.logging.log4j:log4j-core:${Version.log4j2}"
    val log4j2_api              = "org.apache.logging.log4j:log4j-api:${Version.log4j2}"
    val log4j2_slf4j18          = "org.apache.logging.log4j:log4j-slf4j18-impl:${Version.log4j2}"
    val nebula                  = "com.netflix.nebula:gradle-info-plugin:${Version.nebula}"
    val okhttp                  = "com.squareup.okhttp3:okhttp:${Version.okhttp}"
    val opencsv                 = "com.opencsv:opencsv:${Version.opencsv}"
    val rx                      = "io.reactivex.rxjava2:rxjava:${Version.rx}"
    val reactor                 = "io.projectreactor.kotlin:reactor-kotlin-extensions:${Version.reactor}"
    val reactor_addons          = "io.projectreactor.addons:reactor-adapter:3.3.0.RELEASE"
    val slf4j                   = "org.slf4j:slf4j-api:${Version.slf4j}"
    val spring_boot_webflux     = "org.springframework.boot:spring-boot-starter-webflux"
    val spring_boot_log4j2      = "org.springframework.boot:spring-boot-starter-log4j2"
    val spring_boot_security    = "org.springframework.boot:spring-boot-starter-security"
    val spring_boot_gradle      = "org.springframework.boot:spring-boot-gradle-plugin:${Version.spring_boot}"
    val kotlin_allopen          = "org.jetbrains.kotlin:kotlin-allopen:${Version.kotlin}"
    val kotlin_gradle           = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Version.kotlin}"
    val kotlin_stdlib           = "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    val kotlin_reflect          = "org.jetbrains.kotlin:kotlin-reflect:${Version.kotlin}"

    // Test
    val assertj                 = "org.assertj:assertj-core:${Version.assertj}"
    val byte_buddy              = "net.bytebuddy:byte-buddy:${Version.byte_buddy}"
    val junit_api               = "org.junit.jupiter:junit-jupiter-api:${Version.junit}"
    val junit_engine            = "org.junit.jupiter:junit-jupiter-engine:${Version.junit}"
    val junit_params            = "org.junit.jupiter:junit-jupiter-params:${Version.junit}"
    val junit_platform_runner   = "org.junit.platform:junit-platform-runner:${Version.junit_platform}"
    val junit_platform_commons  = "org.junit.platform:junit-platform-commons:${Version.junit_platform}"
    val junit_platform_engine   = "org.junit.platform:junit-platform-engine:${Version.junit_platform}"
    val mockito                 = "org.mockito:mockito-core:${Version.mockito}"
    val mockito_junit           = "org.mockito:mockito-junit-jupiter:${Version.mockito}"
    val mockito_kotlin          = "com.nhaarman.mockitokotlin2:mockito-kotlin:${Version.mockito_kotlin}"
    val rest_assured            = "io.rest-assured:rest-assured:${Version.rest_assured}"
    val spring_boot_test        = "org.springframework.boot:spring-boot-starter-test"
}
// @formatter:on
